ARM-software/golang-utils

changes/202109131145.bugfix, utils/commonerrors/errors.go, utils/commonerrors/errors_test.go
Improved commonerrors `Any` and `None` to comply with `gosec` recommendations.
Also improved the test cases
=> [commonerrors] Improved test cases and fixed gosec reported issue

changes/202111012244.bugfix, utils/filesystem/lockfile.go, utils/filesystem/lockfile_test.go, utils/parallelisation/parallelisation.go, utils/parallelisation/parallelisation_test.go
Fixed a bug in the file locking mechanism:
the heartbeat was stopped after a timeout although this is not intended.
Bug was in `parallelisation` and unit tests were added so that the problem does not occur again
=> Flaky test and bug fixes

changes/202112191650.bugfix, utils/config/service_configuration.go, utils/config/service_configuration_test.go
Fixed a bug introduced for handling flags and their binding to structured configuration fields
=> Clarified flag binding and configuration load and unmarshalling.

changes/202203011026.feature, utils/reflection/reflection.go, utils/reflection/reflection_test.go
- Added a way to get the pointer to a value
=> [Reflection] get the pointer to a value

changes/202205121612.feature, utils/collection/parseLists.go, utils/collection/parseLists_test.go
Add option to run parseListWithCleanup to keep empty lines
Add option to run `ParseListWithCleanupKeepBlankLines` to run `ParseListWithCleanup` but keep empty lines. This is necessary for the VHT Service. Backwards compatible with old versions.
=> :sparkles: [collection] `ParseListWithCleanupKeepBlankLines` as alternative to `ParseListWithCleanup` to keep blank lines

changes/20220525.feature, utils/filesystem/files.go, utils/filesystem/files_test.go
New `filesystem.FilepathStem` function, emulating the behaviour of https://docs.python.org/3.10/library/pathlib.html#pathlib.PurePath.stem
=> Add `FilepathStem` function to filesystem package, emulating Python's Pathlib.Stem behaviour

changes/202206101540.bugfix, utils/filesystem/lockfile.go
[lock file] ensuring context termination is taken into account during retries
=> [lock file] ensuring context termination is taken into account during retries

.golangci.pre-commit.yaml, .golangci.yaml, changes/202207181519.bugfix, changes/202207181802.bugfix, utils/filesystem/limits.go, utils/http/httptest/testing.go
Adding the missing tags on the limit configuration
=> [filesystem] add missing tags on configuration structure

.secrets.baseline, changes/202207290929.feature, utils/config/service_configuration.go, utils/config/service_configuration_test.go
Add utility for generating a list of the environment variables based on a struct that uses mapstructure.
=> Add utility for generating a list of the environment variables based on a struct that uses mapstructure

changes/202208111140.bugfix, utils/git/git.go
Remove TryLock as it isn't available in go1.16
=> Remove TryLock as it isn't available in go1.16

changes/202208131936.feature, utils/filesystem/extendedosfs.go, utils/filesystem/files.go, utils/filesystem/files_posix.go, utils/filesystem/files_test.go, utils/filesystem/files_windows.go, utils/filesystem/filesystem.go, utils/filesystem/interfaces.go, utils/filesystem/lockfile.go, utils/mocks/mock_filesystem.go, utils/platform/os.go
`[filesystem]` get file ownership information.
This is to cover what is discussed here: https://github.com/golang/go/issues/14753
=> ⭐  `[filesystem]` get file ownership

changes/202209211609.bugfix, utils/git/git_clone_test.go
Checking specific number of files in a repository
=> 🔓 `[git]` New test case for git bomb mitigation

changes/202210040057.feature, utils/filesystem/exclusion.go, utils/filesystem/exclusion_test.go, utils/filesystem/files.go, utils/filesystem/files_test.go, utils/filesystem/interfaces.go, utils/filesystem/zip.go, utils/filesystem/zip_test.go, utils/mocks/mock_filesystem.go
Expand APIs in the `filesystem` module to enable `negation patterns`
=> :star: `[filesystem]` Expand APIs to enable `negation patterns`

changes/202210051012.bugfix, utils/filesystem/files.go, utils/filesystem/files_test.go
=> :bug:`filesystem` fix regression with `Subdirectories`

changes/20230105170818.feature, utils/filesystem/files.go, utils/filesystem/files_test.go, utils/filesystem/interfaces.go, utils/go.mod, utils/go.sum
- extended methods for writing and reading files so that they take a context into account and long running actions can be terminated
=> :lock: `[filesystem]` improve file writing and reading robustness

changes/20230121234948.bugfix, utils/collection/pagination/pagination_test.go, utils/collection/pagination/stream.go
=> :bug: `[pagination]` Fix panic in contructor

changes/20230126194148.bugfix, utils/filesystem/files.go, utils/filesystem/files_test.go, utils/filesystem/testing.go, utils/filesystem/zip_test.go
the behaviour of `filesystem.Copy` was not fully aligned with `cp -r` as described in #195 .
This makes sure this misalignment is fixed
=> :bug: `[filesystem]` Align `Copy` behaviour to `cp -r`

changes/20230127113013.bugfix, utils/filesystem/files.go, utils/filesystem/files_test.go
align the `Copy` of files with `cp <files>`
if the destination is a file or having a file name (i.e. with extension), the destination should be a file
cp source.txt dest.txt => dest.txt should be a file with the content of the source
=> :bug: `[filesystem]` align the `Copy` of files with `cp <files>`

CHANGELOG.md, changes/20230130162624.bugfix, changes/20230130162704.doc, changes/20230131184530.feature, utils/filesystem/filepath.go, utils/filesystem/filepath_test.go, utils/filesystem/files.go, utils/filesystem/files_test.go, utils/filesystem/interfaces.go, utils/mocks/mock_filesystem.go, utils/sharedcache/common.go, utils/sharedcache/common_test.go
In some cases such as the copy of files to destination which do not exist, the behaviour of `filesystem.Copy()` as changed to better aligned with `cp -r` was not particularly straightforward and potentially misleading
e.g.
filesystem.Copy("source.txt","does-not-exist") and  filesystem.Copy("source.txt",".does-not-exist") had different behaviours since the type of destination was interpreted differently.
The intention of this PR is to clarify the behaviour of Copy in those circumstances and ensure the behaviour is more intuitive.
=> :bug: Improve the consistency of the behaviour of `copy` 

changes/20230222130436.feature, utils/filesystem/files.go, utils/filesystem/interfaces.go, utils/mocks/mock_filesystem.go
- Added `FileHashWithContext` so that the operation takes into account a context and can be cancelled
=> :sparkles: `[filesystem]` Make file hashing context aware

changes/202305241743.feature, utils/commonerrors/errortest/testing.go, utils/commonerrors/errortest/testing_test.go
-Added error testing utilities
=> :sparkles: Added error testing utilities

changes/20230531171611.feature, utils/go.sum, utils/http/retry.go, utils/http/retry_test.go
- Added `RetryOnError` in the `http` module to generically retry client calls on particular errors
=> :sparkles: `[http]` Added `RetryOnError`

changes/20230606113952.feature, utils/go.mod, utils/go.sum, utils/logs/hclog_logger.go, utils/logs/hclog_logger_test.go
- Defined a logger for using [hclog](https://github.com/hashicorp/go-hclog)
=> :sparkles: `[logs]` hclog logger

changes/20230606144452.feature, utils/logs/hclog_logger.go, utils/logs/hclog_logger_test.go, utils/logs/writer.go
- `[logs]` created a [hclog](https://github.com/hashicorp/go-hclog)'s wrapper over logs.Loggers
=> :sparkles: `[logs]` hclogs wrapper

changes/20230607112032.feature, utils/logs/logr_logger.go, utils/logs/logr_logger_test.go
-  `logs`Add GetLogrLoggerFromContext to fetch a logr.logger  from a context (#271)
---------
=> :sparkles: `logs`Add GetLogrLoggerFromContext

changes/20230609154852.feature, changes/20230609154935.feature, utils/filesystem/embedfs.go, utils/filesystem/embedfs_test.go, utils/filesystem/files.go, utils/filesystem/filesystem.go, utils/filesystem/interfaces.go, utils/filesystem/lockfile.go, utils/filesystem/testdata/embed/test.txt
- `[filesystem]` Created Adapter to `embed.FS` for use of common utilities"
- `[filesystem]` Ability to read the content of an `afero.File`
=> :sparkles: `[filesystem]` Created Adapter to `embed.FS` 

changes/20230705185305.feature, utils/filesystem/filesystem.go, utils/filesystem/iofs.go, utils/filesystem/iofs_test.go, utils/mocks/mock_filesystem.go
-  `[filesystem]` Add utilities to work with `io/fs FS`
=> :sparkles: `[filesystem]` Add utilities to work with `io/fs FS`

changes/20230906170005.feature, utils/filesystem/files.go, utils/filesystem/files_test.go, utils/filesystem/files_windows.go, utils/filesystem/interfaces.go, utils/mocks/mock_filesystem.go
- This PR adds some more utilities to the `filesystem` module to deal with file ownership
=> :sparkles: `[filesystem]` File ownership utilities

changes/20230919122752.bugfix, utils/platform/users.go, utils/platform/users_posix.go, utils/platform/users_test.go, utils/platform/users_windows_amd64.go, utils/platform/users_windows_arm64.go
- Windows on Arm is not supported by dependency and so must be differentiated from Intel Windows
=> :bug: `[platform]` differentiate between the different Windows architectures support

changes/20231010151706.feature, changes/20231010151811.feature, utils/environment/current.go, utils/environment/current_test.go, utils/environment/interfaces.go, utils/mocks/mock_environment.go
-  Add `GetEnvironmentVariable()` to try and fetch specific environment variable
- Support `.env` files
=> ✨ [`environment`] Add GetEnvironmentVariable() to try and fetch specific environment variable

changes/20231013160208.feature, changes/20231013160247.bugfix, utils/environment/current.go, utils/environment/envvar.go, utils/environment/envvar_test.go
- Fix the bug happening when parsing environment variables
- exposed some of the underlying function
=> :bug: `[environment]` Fix environment variable parsing

changes/20231016164922.feature, changes/20231016173631.feature, changes/20231016175953.feature, changes/20231016204910.feature, changes/20231016234712.feature, utils/collection/search.go, utils/collection/search_test.go, utils/platform/cmd.go, utils/platform/cmd_posix.go, utils/platform/cmd_test.go, utils/platform/cmd_windows.go, utils/platform/users.go, utils/platform/users_posix.go, utils/platform/users_test.go, utils/platform/users_windows.go, utils/platform/users_windows_amd64.go, utils/platform/users_windows_arm64.go, utils/subprocess/command/cmd.go, utils/subprocess/command/cmd_test.go
- `[platform]` Added `WithPrivileges` so that commands are elevated with privileges depending on the permissions of the current user
this  is so that commands are redefined automatically to run with `sudo` or `runas` depending on current user permissions
=> :sparkles: Redefine commands depending on user permissions

changes/20231017132731.feature, utils/environment/envvar.go, utils/environment/envvar_test.go
- Exposing validation rule for environment variable keys for use in configuration validation functions
=> :sparkles: `[environment]` Expose validation rule

changes/20231026104543.feature, utils/environment/current.go, utils/platform/users.go, utils/platform/users_test.go
This is calling the os/user APIs but making sure the homedirectory is expanded.
errors returned are also categorised using the commonerrors
=> :sparkles: `[platform]` Ability to get user information

changes/20231027143154.feature, utils/environment/envvar.go, utils/platform/os.go, utils/platform/os_posix.go, utils/platform/os_test.go, utils/platform/os_windows.go
- `os.Expand` is not portable and is not recursive
- Introducing utilities to allow variable expansion on any platform
=> :sparkles: [platform] Variable expansion

changes/20231027081549.feature, utils/logs/quiet_logger.go, utils/logs/quiet_logger_test.go
- Added a logger which only logs errors
=> :sparkles: `[logs]` Add a quiet logger

changes/20231113111138.feature, utils/logs/logrimp/quiet_logger.go, utils/logs/logrimp/quiet_logger_test.go
- Add a quiet logger so that only error messages are logged
=> :sparkles: [`logs`] Add a `logr.Logger` quiet logger to only log errors

changes/20240104152047.feature, utils/filesystem/filepath.go, utils/filesystem/filepath_test.go
These are validation rules for paths.
=> :sparkles: `[filesystem]` Add validation rules for paths

changes/20240118145043.feature, utils/filesystem/files.go, utils/filesystem/files_test.go, utils/git/git_test.go
Conversion method for some usecases where legacy functions require `*os.File` instead of interfaces when working with files
=> :sparkles: `[filesystem]` Add a way to convert `filesystem.File` to `*os.File`

changes/20240131145019.bugfix, changes/20240131151659.bugfix, utils/logs/multiple_logger.go, utils/logs/multiple_logger_test.go, utils/subprocess/executor_test.go, utils/subprocess/testdata/echo_stdout_and_stderr.sh
subprocess.Output results in data race if output prints to both stderr and stdout
=> :bug: `subprocess` subprocess.Output results in data race if output prints to both stderr and stdout

changes/20240131182504.feature, utils/subprocess/command_wrapper.go, utils/subprocess/command_wrapper_test.go, utils/subprocess/executor.go
- this would mean that the environment of the subprocess can now be set up
=> :sparkles: `[subprocess]` Enable specifying additional environment variables for the subprocess to run with

changes/20240403145328.bugfix, changes/20240403150239.feature, utils/platform/deletion.go, utils/proc/process.go, utils/proc/process_test.go, utils/proc/ps_windows.go, utils/subprocess/executor_test.go
- As described in https://github.com/golang/go/issues/24050, processes could be left hanging if not terminated properly. Better process termination was introduced to avoid this phenomenon.
- IsProcessRunning was added to `/proc` to check if a process identified by its pid is currently running.
=> :sparkles: Improve process termination to avoid orphan subprocesses

changes/20240403170926.bugfix, utils/subprocess/command_wrapper.go, utils/subprocess/command_wrapper_darwin.go, utils/subprocess/command_wrapper_linux.go, utils/subprocess/command_wrapper_windows.go, utils/subprocess/executor.go, utils/subprocess/logging.go, utils/subprocess/messaging.go, utils/subprocess/monitoring.go
- Trying to solve how subprocesses are spawned so that their termination is done gracefully and no orphans are left hanging
=> :bug: Fix hanging processes and subprocess termination

.golangci.yaml, changes/20240508124107.feature, utils/logs/pipe_logger.go, utils/logs/pipe_logger_test.go
Add pipe logger for logging output without adding anything to the output
=> :sparkles: Add pipe logger for logging output without adding anything to the output

changes/20240530162101.feature, utils/commonerrors/errors.go, utils/commonerrors/errors_test.go
Add support for warnings in commonerrors
=> :sparkles: `commonerrors` Add support for warnings in commonerrors

changes/20240603130700.feature, utils/http/client_test.go, utils/http/interfaces.go, utils/http/retryable_client.go, utils/http/retryable_client_test.go
Add support for extracting underlying go-retryable client from retryable client. This will allow us to use this retryable client in libraries that want the hashicorp one.
=> :sparkles: `http` Add support for extracting underlying go-retryable client from retryable client

changes/20240604150742.feature, utils/commonerrors/errors.go, utils/commonerrors/errors_test.go
Add support for determining commonerror from a string
=> :sparkles: `commonerrors` Add support for determining commonerror from a string

changes/20240613181738.feature, utils/logs/logr_logger.go, utils/logs/logr_logger_test.go, utils/logs/std_logger.go
=> :sparkles: `[logs]` Add a way to use a `Loggers` as a plain `logr.Logger`

changes/20240619131209.feature, utils/http/client_test.go, utils/http/retryable_client.go, utils/http/retryable_client_test.go
Add support for overriding the default client used by the oath retryable clients
=> :sparkles: `http` Add support for overriding the default client used by the oath retryable clients

changes/20240827111953.feature, utils/collection/parseLists.go, utils/collection/parseLists_test.go
Add support for parsing a comma separated string list as a map of key-value pairs
=> :sparkles: Add support for parsing a comma separated string list as a map of key-value pairs

changes/20240918112214.bugfix, utils/config/service_configuration.go, utils/config/service_configuration_test.go, utils/field/fields_test.go, utils/filesystem/zip.go, utils/retry/retry.go
If using a config file then it was overriding the default values that had already been added to the session. This is fine except if you don't specify a value in the config because it is replaced with an empty value and the defaults are not kept.
With the newly added test, if you do it the old way the test fails.
=> :bug: Make sure that configuration defaults are not over-ridden with blank values when reading in a config file that doesn't specify fields

changes/20241107160700.feature, utils/field/fields_test.go, utils/filesystem/zip.go, utils/idgen/uuid.go, utils/idgen/uuid_test.go, utils/platform/os.go, utils/proc/process.go, utils/reflection/reflection.go, utils/retry/retry.go, utils/safecast/ReadMe.md, utils/safecast/boundary.go, utils/safecast/cast.go, utils/safecast/cast_test.go, utils/safecast/fuzzcast_test.go, utils/safecast/number.go
protect against [CWE-190](https://cwe.mitre.org/data/definitions/190.html)
=> :sparkles: `[safecast]` Introduced utilities to perform casting safely

changes/20241114171420.bugfix, utils/collection/pagination/interfaces.go, utils/collection/pagination/stream.go, utils/collection/pagination/stream_test.go, utils/collection/pagination/testing.go, utils/collection/pagination/testing_test.go
- Streams implementation had some bugs in that the browsing would stop before reaching the end.
- Added a lot more specific stream tests
=> :bug: `[pagination]` Fix stream pagination

changes/20241216151002.feature, utils/field/fields.go, utils/field/fields_test.go
extend `[field]` utilities to use generics
=> :sparkles: [fields] Extends utilities with regards to optional fields

changes/20250108150125.feature, utils/collection/search.go, utils/collection/search_test.go
add utilities to the collection module
=> :sparkles: `[collection]` add helpers easier to use with slices

changes/20250211153712.feature, utils/encryption/aesrsa/encryption.go, utils/encryption/aesrsa/encryption_test.go, utils/encryption/aesrsa/payload.go, utils/encryption/aesrsa/testhelpers/helper.go
This change provides a method of encrypting a payload using hybrid RSA AES encryption. The payload itself is encrypted with the AES key which is fast but symmetric meaning both parties require the key. Therefore the key is encrypted with asymmetric RSA encryption and the encrypted key is included in the payload itself. RSA is not efficient on larger payloads so this method allows for fast encryption whilst also being asymmetric.
Information on hybrid RSA/AES encryption can be found here https://www.ijrar.org/papers/IJRAR23B1852.pdf
=> :sparkles: `encryption` Add support for encrypting content using hybrid RSA/AES encryption

changes/20250227155909.feature, utils/charset/charset.go, utils/charset/mapping.go, utils/charset/unsupportedcharset_index.go, utils/collection/conditions.go, utils/collection/pagination/pagination.go, utils/collection/pagination/stream.go, utils/collection/parseLists.go, utils/commonerrors/errors.go, utils/commonerrors/errors_test.go, utils/commonerrors/serialisation.go, utils/idgen/uuid.go, utils/proc/process.go, utils/retry/retry.go, utils/safeio/error.go, utils/safeio/read.go, utils/semver/semver.go, utils/signing/signing.go
Utilities to help wrapping errors and follow  convention `errorType: reason`
=> :sparkles: `[commonerrors]` Provide utilities to wrap or format errors

.github/workflows/ci.yml, README.md, changes/20250312094629.feature, utils/go.mod
- ⬆️ Upgrade the go version so dependencies can be updated
=> :boom: Upgrade `go` version to `1.23`

changes/20250328120125.bugfix, changes/20250328120920.feature, utils/http/useragent/useragent.go, utils/http/useragent/useragent_test.go, utils/reflection/reflection.go, utils/reflection/reflection_test.go
- Moved utilities to generate user agent header
- Modified the `IsEmpty` behaviour to be more performant with regards to strings
=> :sparkles: `[useragent]` Added a `useragent` module to help generate `User-Agent` header

changes/20250328135041.feature, utils/encryption/aesrsa/encryption.go
Add utility to encrypt payloads using public RSA key directly instead of using the certificate
=> :sparkles: `encryption` Add utility to encrypt payloads using public RSA key directly instead of using the certificate

changes/20250409132457.bugfix, changes/20250409132457.feature, utils/filesystem/filepath.go, utils/filesystem/filepath_test.go, utils/filesystem/files.go
Same function as `filepath.Base` but is aware of the different file systems, mainly solves the issue of how `embed` works with `/` regardless of the OS.
Also, refactored `FilePathJoin` to work the same way.
=> :gear: Add filesytem aware `FilePathBase()` to filepath Utils

changes/20250414165452.feature, utils/units/size/units.go, utils/units/size/units_test.go
Help generating strings from size and parsing size values
=> :sparkles: `[unit]` Add helpers to format memory values and parse strings

changes/20250516124618.feature, utils/collection/parseLists.go, utils/collection/parseLists_test.go
Added a few utilities to convert maps into slices or strings so that they can be serialised easily
=> :sparkles: `[collection]` Add utilities to serialising maps into comma separated strings

changes/20250521081848.bugfix, utils/commonerrors/errors.go, utils/commonerrors/errors_test.go
fix string formatting of errors
=> :bug: `[commonerrors]` fix string representation

.secrets.baseline, changes/20250605081112.feature, changes/20250605083650.feature, utils/environment/current.go, utils/environment/current_test.go, utils/environment/envvar.go, utils/hashing/hash.go, utils/hashing/hash_test.go
- environment: Added utilities to help retrieving multiple variables from the environment
- hashing: Added utilities to help carrying out hashing calculations under the context protection
=> :sparkles: Various small helpers to reduce code duplication

changes/20250708131716.bugfix, utils/validation/rules.go, utils/validation/rules_test.go
Make sure to expose validation rule as a `validation.Rule`
=> :bug: `validation` Make sure to expose validation rule as a `validation.Rule`

changes/20250714171923.bugfix, changes/20250715105927.feature, utils/proc/errors.go, utils/proc/interrupt.go, utils/proc/interrupt_test.go, utils/subprocess/command_wrapper.go, utils/subprocess/executor.go, utils/subprocess/executor_test.go
Improvements about processes cancellation
=> :bug: `[subprocess]` make sure child processes are killed on context cancellation

changes/20250718123400.bugfix, utils/platform/deletion.go, utils/proc/interrupt.go, utils/subprocess/command_wrapper.go, utils/subprocess/supervisor/supervisor.go
Improve the error reported when a process is cancelled
=> :bug: `[subprocess]` Improve the error reporting when a process is cancelled

changes/20250730095330.bugfix, utils/proc/find/find_linux.go
In process find, ignore processes that have stopped between listing and matching
=> :bug: `proc` In process find, ignore processes that have stopped between listing and matching

changes/20250801093542.bugfix, changes/20250801105019.feature, utils/commonerrors/errors.go, utils/commonerrors/errors_test.go, utils/filesystem/extendedosfs.go
Unlink files before attempting to remove them in Remove. This is because for things like socket files the remove will fail if they are linked.
=> :bug: `filesystem` Unlink files before attempting to remove them in Remove

changes/20250807104110.bugfix, utils/proc/find/find_linux.go, utils/proc/find/find_linux_test.go
Make sure that invalid PIDs are ignored when stopping processes
=> :bug: `proc` Make sure that invalid PIDs are ignored when stopping processes

changes/20250807151301.feature, utils/commonerrors/errors.go, utils/commonerrors/errors_test.go, utils/go.mod, utils/go.sum
Add ErrFailed. This is useful because ErrUnexpected is used a lot as a system error even when we are carrying out underlying tasks where a failure isn't an error. This provides us another generic error but one that we can use to distinguish between failures and system errors.
=> :sparkles: `commonerrors` Add ErrFailed

changes/20250814104556.bugfix, utils/parallelisation/onclose.go
- close stores require to be used slightly differently to what they used to.
=> :bug: [parallelisation] Make sure options are not overridden for a close store

changes/20250905171217.feature, changes/20250908111211.feature, utils/collection/range.go, utils/collection/range_test.go, utils/collection/search.go, utils/parallelisation/group.go, utils/parallelisation/parallelisation.go, utils/parallelisation/parallelisation_test.go, utils/parallelisation/transform.go, utils/parallelisation/transform_test.go, utils/signing/signing_test.go
- Add a transform group
- reuse groups to define worker pools
=> :sparkles: `[parallelisation]` Define a transformation group

changes/20250909150027.feature, utils/safeio/copy.go, utils/safeio/copy_test.go, utils/safeio/error.go, utils/safeio/read.go, utils/safeio/read_closer_test.go
Add support for cancelling readers that make blocking kernel reads during copying to safeio submodule.
When copying, a lot of the time things were in the kernel read and therefore since the cancel in the other contextual readers only cancel before a read, they weren't be cancelled.
This allows readclosers to be used and makes it so that context cancellation will call their close functions which will stop the kernel read.
https://man7.org/linux/man-pages/man2/read.2.html
=> :sparkles: `safeio` Add support for cancelling readers that make blocking kernel reads during copying

changes/20250925093723.feature, changes/20250925122057.feature, utils/collection/search.go, utils/collection/search_test.go, utils/hashing/hash.go, utils/http/header_client.go, utils/http/headers/headers.go, utils/http/headers/tus/tus.go, utils/http/headers/tus/tus_test.go
- implement some [TUS](https://tus.io/protocols/resumable-upload) utilities
- add some map utilities
=> :sparkles: `[headers]` support for TUS headers
