.secrets.baseline

Updated the secret baseline for detect-secrets to work correctly

Updated secret baseline record

---

.github/workflows/ci.yml
.github/workflows/release.yml
.gitignore
.secrets.baseline
README.md
changes/202108231725.misc
utils/serialization/testdata/testfile_GB2312.xml

Creating CI

---

changes/202111091652.feature
utils/collection/modify.go
utils/collection/modify_test.go
utils/collection/search.go

Added collection utilities to remove elements from slices

Added collection utilities

---

.secrets.baseline
DEVELOPMENT.md
changes/202112031155.bugfix
changes/202112031255.bugfix
utils/config/service_configuration.go
utils/config/service_configuration_test.go
utils/go.mod
utils/go.sum

fixed flag binding between CLI flags and environment variables

fixed flag binding

---

changes/202112161834.misc
utils/filesystem/files_test.go

Fix failing tests due to random number generation failure.

Fix failing tests

---

changes/202204061624.feature
utils/collection/parseLists.go
utils/collection/parseLists_test.go

[collection] exposing `ParseListWithCleanup`

✨ [collection] exposing `ParseListWithCleanup`

---

changes/202204251958.feature
utils/commonerrors/errors.go

Added common errors to be more specific

✨ Added common errors

---

changes/202204252100.feature
utils/commonerrors/errors.go

✨ Added common error

---

.golangci.pre-commit.yaml
.golangci.yaml
changes/202207201838.misc
utils/charset/charset_test.go
utils/config/service_configuration.go
utils/config/service_configuration_test.go
utils/filesystem/filehash_test.go
utils/filesystem/files.go
utils/filesystem/files_test.go
utils/filesystem/lockfile.go
utils/hashing/hash_test.go
utils/hashing/interfaces.go
utils/http/client_test.go
utils/http/configuration.go
utils/http/interfaces.go
utils/http/retry_configuration.go
utils/http/retryable_client_test.go
utils/logs/string_logger.go
utils/platform/os.go
utils/reflection/reflection.go
utils/subprocess/executor_test.go
utils/subprocess/logging.go

⚙️ Update linters

---

.secrets.baseline
changes/202208111416.bugfix
utils/git/config.go
utils/git/git.go
utils/git/git_clone_test.go
utils/git/git_test.go
utils/git/interfaces.go
utils/hashing/hash.go
utils/hashing/hash_test.go
utils/strings/strings.go
utils/strings/strings_test.go

Refactor git for workspace service compatibility.

`[git]` modified interface to handle more generic references (tag, commit hash or branch name)

---

changes/202208111622.bugfix
utils/git/git.go
utils/git/git_test.go

Return HEAD if reference not provided

[git] Return HEAD if reference not provided

---

changes/202208251445.bugfix
utils/filesystem/files_posix.go

Fix the build configuration so that the platform dependent code actually builds on Linux

:bug: `[filesystem]` Fix platform dependent code`

---

changes/202208311750.bugfix
utils/logs/writer.go

:bug: `[logs]` Fix error message

---

changes/202211301058.doc
utils/git/git.go
utils/git/git_clone_test.go
utils/git/git_test.go

🐛 [git] fix a test

---

changes/202212131259.bugfix
utils/filesystem/files.go

Change move file to copy file not foler

🐛  [filesystem] Change move file to copy file not folder

---

changes/20221228210153.feature
changes/20221228210503.bugfix
utils/collection/pagination/interfaces.go
utils/collection/pagination/pagination.go
utils/collection/pagination/pagination_test.go
utils/collection/pagination/stream.go
utils/collection/pagination/testing.go
utils/mocks/mock_pagination.go

extended paginators to deal with static pages which cannot iterate over themselves

✨ Pagination extension

---

.github/workflows/ci.yml
changes/20230111140925.feature
utils/commonerrors/errors.go
utils/safeio/copy.go
utils/safeio/error.go
utils/safeio/error_test.go
utils/safeio/read.go
utils/safeio/read_test.go
utils/safeio/write.go

Extend the utilities so that writers and readers can be converted

:sparkles: `[safeio]` Extend the utilities

---

.secrets.baseline
changes/20230216115653.misc
changes/20230216115815.feature
utils/filesystem/files.go
utils/sharedcache/common_test.go
utils/sharedcache/sharedcache_immutable_test.go
utils/sharedcache/sharedcache_test.go

:sparkles: `[filesystem]` Expose WriteFile

---

changes/202303011441.misc
pyproject.toml

Hopefully fixes the changelog formatting.

:gear: Update changelog formatting

---

changes/20230428172043.feature
utils/commonerrors/errors.go
utils/commonerrors/errors_test.go

Add IgnoreErrors so that errors can be ignored

:sparkles: `[commonerrors]` Add Ignore so that errors can be ignored

---

changes/20231027170436.feature
utils/environment/current.go
utils/environment/current_test.go
utils/environment/envvar.go
utils/environment/envvar_test.go
utils/environment/interfaces.go
utils/mocks/mock_environment.go

Add abilities to get fully expanded environment variables

:sparkles: [environment] Add utilities to expand environment variables

---

changes/20240220143843.feature
changes/20240220151510.feature
utils/http/retry.go
utils/http/retry_configuration.go
utils/retry/retry.go
utils/retry/retry_configuration.go
utils/retry/retry_configuration_test.go
utils/retry/retry_test.go

Add `RetryIf` function to http retries sub-module to do retries based on an arbitrary condition.
The existing tests already cover the changes so no more have been added.

:sparkles: `http` Add RetryIf function to do retries based on an arbitrary condition

---

changes/20240320185150.feature
utils/proc/errors.go
utils/proc/interfaces.go
utils/proc/process.go
utils/proc/process_test.go
utils/proc/ps_posix.go
utils/proc/ps_windows.go

Add utilities to manage processes

:sparkles: Introduced module `[proc]` for managing processes

---

changes/20240503113230.bugfix
utils/collection/pagination/stream.go

Fix bug in paginators that causes infinite recursion

:bug: `collection` Fix bug in paginators that causes infinite recursion

---

changes/202408141345.misc
utils/git/git_test.go

:gear: Fix linting

---

changes/20240827131009.feature
changes/20240827131050.misc
utils/commonerrors/errors.go
utils/commonerrors/errors_test.go
utils/field/fields_test.go
utils/filesystem/files_test.go
utils/filesystem/zip.go
utils/platform/os.go
utils/proc/process.go
utils/reflection/reflection.go

Fix or add comments about gosec overflow errors and add out of range error to commonerrors.

:wrench: Fix or add comments about gosec overflow errors

---

.goreleaser.yml
changes/20250110141400.misc

:gear: generate sboms

---

changes/20250113134619.feature
utils/collection/conditions.go
utils/collection/conditions_test.go
utils/collection/search.go
utils/collection/search_test.go

- helpers for evaluating flags

:sparkles: `[collections]` Added `Conditions` type to provide a helper to deal with flags or boolean slices

---

changes/20250212110908.bugfix
utils/subprocess/supervisor/supervisor.go
utils/subprocess/supervisor/supervisor_test.go

Make process supervisor more robust by handling errors and undefined commands

:bug: `subprocess` Make process supervisor more robust by handling errors and undefined commands

---

changes/20250516152950.feature
utils/collection/parseLists.go

:sparkles: `[collection]` Expose utilities to convert slices into maps

---

changes/20250529160336.feature
changes/20250529161638.feature
changes/20250529175329.feature
utils/logs/fifo_logger.go
utils/logs/fifo_logger_test.go
utils/subprocess/supervisor/supervisor.go
utils/subprocess/supervisor/supervisor_test.go

Add option to run supervisor a fixed number of times

:sparkles: `supervisor` Add option to run supervisor a fixed number of times

---

.goreleaser.yml
changes/20250925195429.bugfix

This ensures goreleaser yaml complies with version 2 of the tool.

🐛 Update goreleaser yaml to work with version 2
